### ISSUE TITLE
"date must not be in the future or over 5 years ago"

### ISSUE THREAD

**Issue by adamabsurdum** [ivallesp/N26-to-YNAB#1]
Hi – Upon running the `python main.py -a <n26-account-name>` command it manages to pull the transactions from my n26 account, but does not manage to pass it on to ynab... I am unfortunately rather a n00b, so your help would be much appreciated, as it would solve the tedious task of getting n26 transactions into ynab. Please let me know how I can assist!

**Comment by ivallesp** [comment]
Hi, sure, happy to assist and try to help. Can you try to share with me what are the error messages you get? I am running this system daily and it works like a charm for me

**Comment by ivallesp** [comment]
Can you please share the logs? Please check there's no confidential info there

**Comment by adamabsurdum** [comment]
[n26-to-ynab_log.txt](https://github.com/ivallesp/N26-to-YNAB/files/6966465/n26-to-ynab_log.txt)

Please find the log attached! Thanks for the swift response!

**Comment by ivallesp** [comment]
Oh! The problem seems to be that you have a n26 account from long time ago!
YNAB apparently does not allow to add transactions from >5Y ago so it is
dumping that error. We should filter transactions that are > 5Y old. I will
try to find time to do it as soon as I can :)

**Comment by adamabsurdum** [comment]
Yeah, I guess I am what they call a 'first mover' :)

Looking forward to the fix. Thanks so much!

**Comment by adamabsurdum** [comment]
Hi Iván — did you already have time to look into this? Thanks in advance!

**Comment by adamabsurdum** [comment]
Hey Iván — after trying basically every other solution to bring together YNAB and N26 I find myself still yearning about yours :)

If you don't have time to fix it, can you point me into the right direction, so I can try it myself? Thanks in advance.

**Comment by ivallesp** [comment]
Hey @adamabsurdum, sorry for the delay. This should be fixed in commit #0f67f7. Please pull and try to see if it works now. I have filtered transactions older than 5Years.

I am closing this issue, please feel free to reopen or reply if the problem still persists.

Best!

**Comment by adamabsurdum** [comment]
Thanks so much! It works like a charm! 

YIPPIE :)
